language: en
pipeline: spacy_sklearn
policies:
- name: MappingPolicy
- name: KerasPolicy
  epochs: 100
  max_history: 5
- name: MemoizationPolicy
  max_history: 3
- name: FallbackPolicy
  nlu_threshold: 0.3
  core_threshold: 0.3
  fallback_action_name: action_default_fallback
