language: en
pipeline: spacy_sklearn
# pipeline: supervised_embeddings
# pipeline:
    # - name: "nlp_spacy"
    # - name: "tokenizer_spacy"
    # - name: "intent_entity_featurizer_regex"
    # - name: "intent_featurizer_spacy"
    # - name: "ner_spacy"
    # - name: "ner_crf"
    # - name: "ner_synonyms"
    # - name: "intent_classifier_sklearn"
policies:
  - name: MappingPolicy
  - name: KerasPolicy
    epochs: 100
    max_history: 5  
  - name: MemoizationPolicy
    max_history: 3
  - name: FallbackPolicy
    # min confidence needed to accept an NLU prediction
    nlu_threshold: 0.3
    # min confidence needed to accept an action prediction from Rasa Core
    core_threshold: 0.3
    # name of the action to be called if the confidence of intent / action
    # is below the threshold
    fallback_action_name: 'action_default_fallback'  